mendersoftware/iot-manager

.gitlab-ci.yml, config.yaml, main.go, store/mongo/migrations.go
=> Drop the "AZURE" prefix in env variables and mongodb database name

docs/management.yml
This PR contains the management API specifications for the new `iot-manager` service.
=> docs: Define required management APIs

api/http/management.go, api/http/management_external_test.go, api/http/management_state.go, api/http/management_state_test.go, api/http/management_test.go, api/http/router.go, app/app.go, app/app_iot_hub.go, app/app_iot_hub_test.go, app/app_test.go, app/mocks/App.go, model/device.go, model/state.go, store/datastore.go, store/mocks/DataStore.go, store/mongo/datastore_mongo.go, store/mongo/datastore_mongo_test.go
=> MEN-5322: implement the IoT Manager Device State management APIs

app/app_iot_hub.go, app/app_iot_hub_test.go, client/iothub/client.go, client/iothub/model.go
=> MEN-5322: Replace IoT Hub device twin's properties on device state update

api/http/internal.go, api/http/internal_test.go, api/http/management.go, api/http/management_state.go, api/http/management_state_test.go, api/http/management_test.go, api/http/router.go, app/app.go, app/app_iot_hub.go, app/app_iot_hub_test.go, app/app_test.go, app/mocks/App.go, docs/management.yml, model/status.go, store/datastore.go, store/mocks/DataStore.go, store/mongo/datastore_mongo.go, store/mongo/datastore_mongo_test.go
=> Various fixes and improvements to iot-manager

api/http/management.go, api/http/management_test.go, api/http/router.go, app/app.go, app/app_test.go, app/mocks/App.go, store/datastore.go, store/mocks/DataStore.go, store/mongo/datastore_mongo.go, store/mongo/datastore_mongo_test.go
Add possibility to set integration credentials and remove whole integration
Changelog: title
Signed-off-by: Maciej Tomczuk <maciej.tomczuk@northern.tech>
=> Add possibility to set integration credentials and remove whole integration

app/app.go, app/app_iot_hub.go, app/app_iot_hub_test.go, config.yaml, crypto/crypto.go, crypto/crypto_test.go, crypto/string_test.go, main.go
Depends on: https://github.com/mendersoftware/integration/pull/1854
=> MEN-5367: follow-ups

tests/run.sh, utils/mockgen.sh
Ticket: None
Signed-off-by: Peter Grzybowski <peter@northern.tech>
=> chore: license fix for .sh files.

crypto/string.go, crypto/string_test.go, model/aws_credentials_test.go
=> fix: do not marshall the AWS secret access key to JSON

app/app.go, app/app_iot_core_test.go, app/app_iot_hub_test.go, app/app_test.go
Changelog: Title
Ticket: MEN-5832
=> fix: Fire webhook independent if device was provisioned

client/client.go, client/client_test.go, client/iothub/client.go
chore(webhooks): Add Content-Type header to webhook requests
Changelog: None
Ticket: None
Signed-off-by: Maciej Tomczuk <maciej.tomczuk@northern.tech>
=> chore(webhooks): Add Content-Type header to webhook requests

client/iotcore/client.go, client/iotcore/client_test.go, tests/tests/test_sync_aws_iotcore.py
Ticket: [MEN-6001](https://tracker.mender.io/browse/MEN-6001)
=> iot core client: wait for principal detachment to propagate when deleting device

tests/requirements.txt
https://northerntech.atlassian.net/browse/QA-593
=> Acceptance test fix: urlib3

.gitlab-ci.yml
=> fix: build incompat with alpine 3.18 - revert to 3.17

api/http/internal.go, api/http/internal_test.go, api/http/router.go, app/app.go, app/app_iot_hub.go, app/app_iot_hub_test.go, app/app_test.go, app/mocks/App.go, model/provider.go
Ticket: [ALV-72](https://northerntech.atlassian.net/browse/ALV-72)
[ALV-72]: https://northerntech.atlassian.net/browse/ALV-72?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> internal authorization endpoint

.gitlab-ci.yml
=> Fix Production rolling release

.gitlab-ci.yml
=> Alvaldi: don't deploy staging from a production pipeline

.gitlab-ci.yml
Ticket: QA-642
Changelog: None
=> Downstream pipeline failures workaround

client/iotcore/client.go, tests/mmock/config/test_sync_aws_iotcore/iotcore_attach_things_principals.yml, tests/mmock/config/test_sync_aws_iotcore/iotcore_delete_certificate.yml, tests/mmock/config/test_sync_aws_iotcore/iotcore_delete_things.yml, tests/mmock/config/test_sync_aws_iotcore/iotcore_delete_things_principals.yml, tests/mmock/config/test_sync_aws_iotcore/iotcore_update_certificate_active.yml, tests/mmock/config/test_sync_aws_iotcore/iotcore_update_certificate_inactive.yml, tests/tests/test_sync_aws_iotcore.py
This reverts commit 122311a439906c116c39c59ab6a5130df052b19c.
Changelog: None
Ticket: QA-582
=> revert: "test: Skip TestSyncAWSIoTCore.test_sync for the time being."

.gitlab-ci.yml
=> ci: update gitlab runners shared tags
